### PR TITLE
msm_mpdecision and bt

### PR DESCRIPTION
**Pull request by ericfrs**
Please also check device common pull request, thanks.

### CODE REVIEW

**Comment by chil360** [comment]
In-kernel mpdecision - why? I thought intelliplug was working well.

**Comment by ericfrs** [comment]
A lot of users tell me that IntelliPlug only decrease the performance on LP.. at first i didn't think but..

I'm on resurrection with it about 3 days ago and, yes, work fine, also some games run without the tipycal "frozen screen". I don't pay attention of  battery life but it looks good.

At least for now i'll still using msm_mp

I do not know if I'll stay with it or return to Intelliplug..

**Comment by chil360** [comment]
With these patches, there's no problem with both intelliplug & mpdecision in the same kernel? And can easily switch between the two?

**Comment by ericfrs** [comment]
On intelliplug all is defined at CONFIG_...blablabla.. There's not problem with both hotplug if you have only msm_mp enabled.. Otherwise, if u want to use intelliplug you should remove msm_mp

Anyway in the future if i decide to use msm_mp i'll remove intelliplug.

**Comment by chil360** [comment]
I have merged the bluetooth commits but will hold off on mpdecision for now. Let me know when you have had chance to evaluate intelliplug vs mpdecision and I will follow what you recommend.

**Comment by ericfrs** [comment]
Ok, it's a good idea

**Comment by ericfrs** [comment]
Stay with intelliplug.. I'm still working on msm_mp but don't work as it should.. as i want.

**Pull request closed without merging**
